import initAnimaNumeros from "./modules/anima-numeros";
import initAccordion from "./modules/accordion";
import initDropdown from "./modules/dropdown";
import initFetchAnimais from "./modules/fetch-animais";
import initFetchBitcoin from "./modules/fetch-bitcoin";
import initFuncionamento from "./modules/funcionamento";
import initMenuMobile from "./modules/menu-mobile";
import initModal from "./modules/modal";
import initAnimacaoScroll from "./modules/scroll-animacao";
import initScrollSuave from "./modules/scroll-suave";
import initTabNav from "./modules/tabNav";
import initTooltip from "./modules/tooltip";

initAccordion();
initDropdown();
initAnimaNumeros();
initFetchAnimais();
initFetchBitcoin();
initFuncionamento();
initMenuMobile();
initModal();
initAnimacaoScroll();
initScrollSuave();
initTabNav();
initTooltip();
