import initAnimaNumeros from "./modules/anima-numeros.js";
import initAccordion from "./modules/accordion.js";
import initDropdown from "./modules/dropdown.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";
import initFuncionamento from "./modules/funcionamento.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initModal from "./modules/modal.js";
import initAnimacaoScroll from "./modules/scroll-animacao.js";
import initScrollSuave from "./modules/scroll-suave.js";
import initTabNav from "./modules/tabNav.js";
import initTooltip from "./modules/tooltip.js";

initAccordion();
initDropdown();
initAnimaNumeros();
initFetchAnimais();
initFetchBitcoin();
initFuncionamento();
initMenuMobile();
initModal();
initAnimacaoScroll();
initScrollSuave();
initTabNav();
initTooltip();
